spring:
  rabbitmq:
    addresses: 192.168.20.57:5672
    username: guest
    password: guest
#    listener:
#      simple:
#        acknowledge-mode: manual
#        concurrency: 5
#        max-concurrency: 10
server:
  port: 10010

