
spring:
  application:
    name: springcloud-sample-consumer
  datasource:
    url: jdbc:mysql://192.168.20.190:3306/caytest2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
  #  data:
  #    mongodb:
  #      uri: mongodb://10.37.147.250:27017,10.37.147.250:27017
  cloud:
    zookeeper:
      connectString: localhost:2181

server:
  port: 7080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/


ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 15000
  MaxAutoRetries: 0

mybatis:
  type-aliases-package: com.bytesvc.consumer.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30