spring:
  application:
    name: springcloud-sample-provider
  datasource:
    url: jdbc:mysql://192.168.20.190:3306/caytest?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: org.apache.commons.dbcp2.BasicDataSource
  #  data:
  #    mongodb:
  #      uri: mongodb://10.37.147.250:27017/bytetcc
server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/


  cloud:
    zookeeper:
      connectString: localhost:2181
