
spring:
  application:
    name: spring-dlock
  aop:
    proxy-target-class: true
    auto: true
  cache:
    type: redis
  redis:
    database: 0
    host: 192.168.20.190
    port: 6379
    password:
logging:
  level:
    org.cay.play: debug